name: Build and Deploy
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version from tag
        run: echo "APP_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Install and Build
        env:
          USE_META_CONFIGURATOR_BASE_PATH: true  # Set to true for GitHub Pages deployment
          VITE_FRONTEND_HOSTNAME: https://metaconfigurator.github.io/meta-configurator
          VITE_APP_VERSION: ${{ env.APP_VERSION }}
        run: |
          cd meta_configurator
          npm ci
          npm run build
          cd dist
          cp index.html 404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: meta_configurator/dist
          branch: gh-pages
          target-folder: docs
